// ==========================================
// BANCO DE DADOS DE BOTS PARA RANKING E CLÃS
// ==========================================
const dbBotsRanking = [
    // --- TOP TIER (ENDGAME) ---
    { nome: "Slayer", classe: "Duelist", nivel: 80, olympiadPoints: 2150, vitorias: 300, derrotas: 120 },
    { nome: "MysticKing", classe: "Archmage", nivel: 78, olympiadPoints: 2050, vitorias: 280, derrotas: 150 },
    { nome: "DarkElf99", classe: "Phantom Summoner", nivel: 77, olympiadPoints: 1980, vitorias: 250, derrotas: 180 },
    { nome: "Legolas", classe: "Spellsinger", nivel: 75, olympiadPoints: 1850, vitorias: 210, derrotas: 190 },
    { nome: "OrcSmash", classe: "Dominator", nivel: 76, olympiadPoints: 1720, vitorias: 190, derrotas: 160 },
    { nome: "HealerPro", classe: "Bishop", nivel: 74, olympiadPoints: 1650, vitorias: 175, derrotas: 140 },
    { nome: "ShadowBlade", classe: "Adventurer", nivel: 72, olympiadPoints: 1550, vitorias: 160, derrotas: 150 },
    { nome: "IronWall", classe: "Phoenix Knight", nivel: 70, olympiadPoints: 1420, vitorias: 140, derrotas: 120 },
    { nome: "DeathBringer", classe: "Hell Knight", nivel: 79, olympiadPoints: 1900, vitorias: 220, derrotas: 110 },
    { nome: "StormQueen", classe: "Storm Screamer", nivel: 77, olympiadPoints: 1800, vitorias: 200, derrotas: 130 },
    { nome: "GhostWalker", classe: "Ghost Hunter", nivel: 78, olympiadPoints: 1950, vitorias: 240, derrotas: 140 },
    { nome: "SaintEva", classe: "Eva's Saint", nivel: 76, olympiadPoints: 1700, vitorias: 180, derrotas: 150 },
    { nome: "TitanGod", classe: "Titan", nivel: 80, olympiadPoints: 2200, vitorias: 310, derrotas: 100 },
    { nome: "WindRiderX", classe: "Wind Rider", nivel: 75, olympiadPoints: 1650, vitorias: 160, derrotas: 140 },
    { nome: "SoulTaker", classe: "Soultaker", nivel: 79, olympiadPoints: 2000, vitorias: 270, derrotas: 160 },
    { nome: "MoonlightX", classe: "Moonlight Sentinel", nivel: 77, olympiadPoints: 1850, vitorias: 210, derrotas: 170 },
    
    // --- MID TIER (A/B GRADE) ---
    { nome: "FireStorm", classe: "Sorcerer", nivel: 68, olympiadPoints: 1350, vitorias: 125, derrotas: 110 },
    { nome: "RangerD", classe: "Silver Ranger", nivel: 65, olympiadPoints: 1280, vitorias: 110, derrotas: 95 },
    { nome: "DoomBring", classe: "Doomcryer", nivel: 62, olympiadPoints: 1150, vitorias: 90, derrotas: 80 },
    { nome: "TitanX", classe: "Titan", nivel: 60, olympiadPoints: 1050, vitorias: 85, derrotas: 85 },
    { nome: "SpellMaster", classe: "Spellhowler", nivel: 55, olympiadPoints: 950, vitorias: 70, derrotas: 60 },
    { nome: "TankerPro", classe: "Temple Knight", nivel: 58, olympiadPoints: 1000, vitorias: 75, derrotas: 70 },
    { nome: "Bladedancer9", classe: "Bladedancer", nivel: 52, olympiadPoints: 850, vitorias: 60, derrotas: 55 },
    { nome: "SwordsingerL", classe: "Swordsinger", nivel: 54, olympiadPoints: 900, vitorias: 65, derrotas: 60 },
    { nome: "ProphetX", classe: "Prophet", nivel: 56, olympiadPoints: 920, vitorias: 68, derrotas: 62 },
    { nome: "BountyHunterX", classe: "Bounty Hunter", nivel: 50, olympiadPoints: 800, vitorias: 55, derrotas: 50 },
    { nome: "WarsmithG", classe: "Warsmith", nivel: 51, olympiadPoints: 820, vitorias: 58, derrotas: 52 },
    
    // --- LOW TIER (C/D GRADE) ---
    { nome: "SummonBoi", classe: "Warlock", nivel: 52, olympiadPoints: 850, vitorias: 60, derrotas: 55 },
    { nome: "PVPKng", classe: "Gladiator", nivel: 48, olympiadPoints: 750, vitorias: 50, derrotas: 45 },
    { nome: "NoobKiller", classe: "Assassin", nivel: 45, olympiadPoints: 650, vitorias: 40, derrotas: 35 },
    { nome: "AdenaFarmer", classe: "Scavenger", nivel: 40, olympiadPoints: 550, vitorias: 30, derrotas: 30 },
    { nome: "xXGokuXx", classe: "Rogue", nivel: 35, olympiadPoints: 450, vitorias: 25, derrotas: 30 },
    { nome: "MageGirl", classe: "Elven Wizard", nivel: 30, olympiadPoints: 350, vitorias: 15, derrotas: 25 },
    { nome: "Newbie", classe: "Fighter", nivel: 20, olympiadPoints: 250, vitorias: 10, derrotas: 20 },
    { nome: "LostSoul", classe: "Cleric", nivel: 10, olympiadPoints: 50, vitorias: 1, derrotas: 10 },
    
    // --- ADICIONADOS PARA DINÂMICA DE CLÃS (MAIS REAIS) ---
    { nome: "Arthas", classe: "Paladin", nivel: 76, olympiadPoints: 1750, vitorias: 180, derrotas: 130 },
    { nome: "Illidan", classe: "Abyss Walker", nivel: 77, olympiadPoints: 1820, vitorias: 195, derrotas: 140 },
    { nome: "Gandalf", classe: "Archmage", nivel: 79, olympiadPoints: 1980, vitorias: 230, derrotas: 150 },
    { nome: "Sylvanas", classe: "Phantom Ranger", nivel: 75, olympiadPoints: 1680, vitorias: 150, derrotas: 130 },
    { nome: "Ragnar", classe: "Dreadnought", nivel: 78, olympiadPoints: 1900, vitorias: 210, derrotas: 160 },
    { nome: "Lagertha", classe: "Sword Muse", nivel: 76, olympiadPoints: 1720, vitorias: 170, derrotas: 140 },
    { nome: "Uther", classe: "Phoenix Knight", nivel: 77, olympiadPoints: 1800, vitorias: 190, derrotas: 150 },
    { nome: "Jaina", classe: "Mystic Muse", nivel: 79, olympiadPoints: 2050, vitorias: 260, derrotas: 145 },
    { nome: "Guldan", classe: "Soultaker", nivel: 80, olympiadPoints: 2180, vitorias: 305, derrotas: 125 },
    { nome: "Thrall", classe: "Dominator", nivel: 78, olympiadPoints: 1920, vitorias: 215, derrotas: 155 },
    { nome: "Rexxar", classe: "Titan", nivel: 77, olympiadPoints: 1880, vitorias: 205, derrotas: 145 },
    { nome: "Malfurion", classe: "Elemental Master", nivel: 76, olympiadPoints: 1740, vitorias: 175, derrotas: 135 },
    { nome: "Tyrande", classe: "Moonlight Sentinel", nivel: 78, olympiadPoints: 1960, vitorias: 225, derrotas: 150 },
    { nome: "Baine", classe: "Destroyer", nivel: 75, olympiadPoints: 1620, vitorias: 140, derrotas: 120 },
    { nome: "Voljin", classe: "Doomcryer", nivel: 76, olympiadPoints: 1710, vitorias: 165, derrotas: 145 },
    { nome: "Anduin", classe: "Cardinal", nivel: 79, olympiadPoints: 2010, vitorias: 250, derrotas: 140 },
    { nome: "Varian", classe: "Duelist", nivel: 80, olympiadPoints: 2250, vitorias: 320, derrotas: 115 },
    { nome: "Khadgar", classe: "Archmage", nivel: 77, olympiadPoints: 1840, vitorias: 200, derrotas: 140 },
    { nome: "Maiev", classe: "Ghost Hunter", nivel: 78, olympiadPoints: 1940, vitorias: 235, derrotas: 145 },
    { nome: "Akama", classe: "Grand Khavatari", nivel: 76, olympiadPoints: 1730, vitorias: 175, derrotas: 140 },
    
    // --- MAIS BOTS MID/LOW PARA ENCHER OS CLÃS ---
    { nome: "Zezinho", classe: "Warrior", nivel: 25, olympiadPoints: 300, vitorias: 15, derrotas: 15 },
    { nome: "Fulano", classe: "Human Wizard", nivel: 28, olympiadPoints: 350, vitorias: 18, derrotas: 20 },
    { nome: "Cicrano", classe: "Cleric", nivel: 22, olympiadPoints: 280, vitorias: 12, derrotas: 18 },
    { nome: "Beltrano", classe: "Rogue", nivel: 32, olympiadPoints: 420, vitorias: 22, derrotas: 25 },
    { nome: "Dunga", classe: "Artisan", nivel: 20, olympiadPoints: 220, vitorias: 8, derrotas: 12 },
    { nome: "Mestre", classe: "Scavenger", nivel: 24, olympiadPoints: 290, vitorias: 14, derrotas: 16 },
    { nome: "Soneca", classe: "Dark Wizard", nivel: 26, olympiadPoints: 310, vitorias: 16, derrotas: 14 },
    { nome: "Feliz", classe: "Orc Raider", nivel: 30, olympiadPoints: 400, vitorias: 20, derrotas: 20 },
    { nome: "Atchim", classe: "Monk", nivel: 31, olympiadPoints: 410, vitorias: 21, derrotas: 22 },
    { nome: "Zangado", classe: "Elven Scout", nivel: 29, olympiadPoints: 380, vitorias: 19, derrotas: 19 },
    { nome: "Thor", classe: "Destroyer", nivel: 45, olympiadPoints: 680, vitorias: 45, derrotas: 40 },
    { nome: "Odin", classe: "Overlord", nivel: 48, olympiadPoints: 720, vitorias: 48, derrotas: 42 },
    { nome: "Loki", classe: "Abyss Walker", nivel: 42, olympiadPoints: 620, vitorias: 40, derrotas: 38 },
    { nome: "Hela", classe: "Spellhowler", nivel: 44, olympiadPoints: 650, vitorias: 42, derrotas: 40 },
    { nome: "Tyr", classe: "Paladin", nivel: 46, olympiadPoints: 690, vitorias: 46, derrotas: 44 },
    { nome: "Freya", classe: "Spellsinger", nivel: 43, olympiadPoints: 640, vitorias: 41, derrotas: 39 },
    { nome: "Baldur", classe: "Gladiator", nivel: 47, olympiadPoints: 710, vitorias: 47, derrotas: 45 },
    { nome: "Heimdall", classe: "Human Knight", nivel: 41, olympiadPoints: 610, vitorias: 39, derrotas: 37 },
    { nome: "Vader", classe: "Dark Avenger", nivel: 55, olympiadPoints: 980, vitorias: 75, derrotas: 65 },
    { nome: "Luke", classe: "Paladin", nivel: 52, olympiadPoints: 920, vitorias: 68, derrotas: 60 },
    { nome: "Leia", classe: "Eva's Saint", nivel: 54, olympiadPoints: 940, vitorias: 70, derrotas: 62 },
    { nome: "HanSolo", classe: "Hawkeye", nivel: 53, olympiadPoints: 930, vitorias: 69, derrotas: 61 },
    { nome: "Chewie", classe: "Titan", nivel: 56, olympiadPoints: 960, vitorias: 72, derrotas: 64 },
    { nome: "Yoda", classe: "Mystic Muse", nivel: 60, olympiadPoints: 1050, vitorias: 85, derrotas: 75 },
    { nome: "MaceWindu", classe: "Duelist", nivel: 58, olympiadPoints: 1020, vitorias: 80, derrotas: 70 },
    { nome: "BobaFett", classe: "Bounty Hunter", nivel: 50, olympiadPoints: 850, vitorias: 60, derrotas: 55 },
    
    // --- ADICIONANDO MAIS 20 BOTS PARA TOTALIZAR ~80 ---
    { nome: "Spartacus", classe: "Duelist", nivel: 70, olympiadPoints: 1450, vitorias: 130, derrotas: 110 },
    { nome: "Leonidas", classe: "Dreadnought", nivel: 72, olympiadPoints: 1520, vitorias: 145, derrotas: 125 },
    { nome: "Xena", classe: "Spectral Dancer", nivel: 71, olympiadPoints: 1480, vitorias: 135, derrotas: 115 },
    { nome: "Hercules", classe: "Titan", nivel: 74, olympiadPoints: 1600, vitorias: 165, derrotas: 135 },
    { nome: "Achilles", classe: "Adventurer", nivel: 73, olympiadPoints: 1550, vitorias: 155, derrotas: 130 },
    { nome: "Perseus", classe: "Ghost Sentinel", nivel: 70, olympiadPoints: 1420, vitorias: 125, derrotas: 105 },
    { nome: "Medusa", classe: "Soultaker", nivel: 75, olympiadPoints: 1650, vitorias: 175, derrotas: 140 },
    { nome: "Athena", classe: "Cardinal", nivel: 76, olympiadPoints: 1700, vitorias: 185, derrotas: 145 },
    { nome: "Ares", classe: "Hell Knight", nivel: 78, olympiadPoints: 1850, vitorias: 215, derrotas: 155 },
    { nome: "Hades", classe: "Shillien Templar", nivel: 79, olympiadPoints: 1950, vitorias: 245, derrotas: 165 },
    { nome: "Zeus", classe: "Storm Screamer", nivel: 80, olympiadPoints: 2100, vitorias: 295, derrotas: 135 },
    { nome: "Poseidon", classe: "Mystic Muse", nivel: 79, olympiadPoints: 1980, vitorias: 255, derrotas: 150 },
    { nome: "Artemis", classe: "Moonlight Sentinel", nivel: 77, olympiadPoints: 1800, vitorias: 205, derrotas: 140 },
    { nome: "Apollo", classe: "Sagittarius", nivel: 78, olympiadPoints: 1880, vitorias: 225, derrotas: 145 },
    { nome: "Hermes", classe: "Wind Rider", nivel: 75, olympiadPoints: 1620, vitorias: 155, derrotas: 125 },
    { nome: "Demeter", classe: "Eva's Saint", nivel: 74, olympiadPoints: 1580, vitorias: 145, derrotas: 120 },
    { nome: "Hephaestus", classe: "Maestro", nivel: 73, olympiadPoints: 1540, vitorias: 135, derrotas: 115 },
    { nome: "Dionysus", classe: "Dominator", nivel: 76, olympiadPoints: 1720, vitorias: 190, derrotas: 145 },
    { nome: "Hestia", classe: "Shillien Saint", nivel: 75, olympiadPoints: 1640, vitorias: 170, derrotas: 135 },
    { nome: "Cronus", classe: "Spectral Master", nivel: 78, olympiadPoints: 1900, vitorias: 230, derrotas: 150 }
];

window.dbBotsRanking = dbBotsRanking;
